spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cleanarchitecture?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCOmpliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: password
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-timeout: 30000
      maximum-pool-size: 200
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1;
      validation-timeout: 28000
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    generate-ddl: false
    open-in-view: false
    properties:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
logging:
  level:
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug